services:
  app:
    env_file:
      - ./.env
    container_name: "wa-bot"
    working_dir: /app
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - .wwebjs_auth:/app
      # - .wwebjs_cache:/app
      - vscode-extensions:/root/.vscode-server/extensions

    networks:
      - wabot

networks:
  wabot:
    name: wabot_network

volumes:
  app:
  vscode-extensions: